[tool.poetry]
name = "worm-cyoa-v6-fork"
version = "1.0.0"
description = ""
authors = ["Laureline David <ltouroumov@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.11"
rich = "*"
pillow = "*"
humanize = "*"
lenses = "^1.1.0"
requests = "^2.27.1"
asciidag = "^0.2.0"

[tool.poetry.dev-dependencies]
autopep8 = "^1.6.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
